In [1]:
L = list(range(10))

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [4]:
L2 = [str(c) for c in L]

In [5]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(L2[0])

str

In [7]:
L3 = [True, "2", 3.0, 4]

In [8]:
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
#P41↓

In [10]:
import array

In [12]:
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
import numpy as np

In [16]:
# Integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [18]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [19]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [20]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.random.random((3, 3))

array([[0.7751993 , 0.96359013, 0.05232174],
       [0.86731317, 0.2918835 , 0.28041752],
       [0.99674337, 0.28985632, 0.62198427]])

In [28]:
np.random.normal(0, 1, (3, 3))

array([[-0.69924318, -0.22087241,  1.1157898 ],
       [ 0.33957266,  1.68547202, -0.20076319],
       [ 0.21894178, -1.25179606, -0.34592998]])

In [29]:
np.random.randint(0, 10, (3, 3))

array([[0, 0, 3],
       [5, 4, 6],
       [3, 6, 2]], dtype=int32)

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.empty(3)

array([1., 1., 1.])