In [1]:
import numpy as np

In [7]:
rng = np.random.default_rng()

In [8]:
L = rng.random(100)
sum(L)

np.float64(51.41447638383764)

In [10]:
np.sum(L)

np.float64(51.414476383837666)

In [12]:
big_array = rng.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

51.8 ms ± 1.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
237 μs ± 6.49 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
min(big_array), max(big_array)

(np.float64(1.537729711120761e-06), np.float64(0.9999990367733766))

In [15]:
np.min(big_array), np.max(big_array)

(np.float64(1.537729711120761e-06), np.float64(0.9999990367733766))

In [16]:
%timeit min(big_array)
%timeit np.min(big_array)

35.4 ms ± 243 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
138 μs ± 1.75 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [17]:
print(big_array.min(), big_array.max(), big_array.sum())

1.537729711120761e-06 0.9999990367733766 500131.38225739426


In [18]:
M = rng.integers(0, 10, (3, 4))

In [19]:
print(M)

[[5 0 1 2]
 [9 6 2 6]
 [8 6 6 8]]


In [20]:
M.sum()

np.int64(59)

In [21]:
M.min(axis=0)

array([5, 0, 1, 2])

In [22]:
M.max(axis=1)

array([5, 9, 8])

In [23]:
!head -4 data/president_heights.csv

'head' �́A�����R�}���h�܂��͊O���R�}���h�A
����”\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
