In [7]:
v = [1, 2, 3, 4, 5]

In [8]:
import numpy as np

In [9]:
a = np.array(v)

In [10]:
a

array([1, 2, 3, 4, 5])

In [11]:
type(a)

numpy.ndarray

In [12]:
2 * a

array([ 2,  4,  6,  8, 10])

In [14]:
0.5 * a + 2

array([2.5, 3. , 3.5, 4. , 4.5])

In [15]:
a = np.arange(12).reshape((4, 3))

In [16]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
2 * a

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [ ]:
a ** 2 #2乗

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [19]:
a.mean()

np.float64(5.5)

In [20]:
np.mean(a)

np.float64(5.5)

In [21]:
a.mean(axis=0)

array([4.5, 5.5, 6.5])

In [22]:
np.mean(a, axis=1)

array([ 1.,  4.,  7., 10.])