In [9]:
import numpy as np

In [10]:
rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3, 4))
x3 = rng.integers(10, size=(3, 4, 5)) 

In [11]:
print("x3 ndim: ", x3.ndim )
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:    int64


In [12]:
x1

array([9, 4, 0, 3, 8, 6])

In [13]:
x1[0]

np.int64(9)

In [14]:
x1[4]

np.int64(8)

In [15]:
x1[-1]

np.int64(6)

In [16]:
x1[-2]

np.int64(8)

In [17]:
x2


array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [18]:
x2[0, 0]

np.int64(3)

In [19]:
x2[2, 0]

np.int64(0)

In [20]:
x2[2, -1]

np.int64(9)

In [21]:
x2[0,0] = 12

In [22]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [23]:
x1[0] = 3.14159

In [24]:
x1

array([3, 4, 0, 3, 8, 6])

In [25]:
#P47↓

In [27]:
x1

array([3, 4, 0, 3, 8, 6])

In [28]:
x1[:3]

array([3, 4, 0])

In [29]:
x1[3:]

array([3, 8, 6])

In [30]:
x1[1:4]

array([4, 0, 3])

In [31]:
x1[::2]

array([3, 0, 8])

In [32]:
x1[1::2]

array([4, 3, 6])

In [33]:
x1[::-1]

array([6, 8, 3, 0, 4, 3])

In [36]:
x1[4::-2]

array([8, 0, 3])

In [37]:
#P48↓

In [38]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [40]:
x2[:2, :3] #最初の2行と最初の3列

array([[12,  1,  3],
       [ 4,  0,  2]])

In [42]:
x2[:3, ::2]

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [43]:
x2[::-1, ::-1]

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [44]:
x2[:, 0]

array([12,  4,  0])

In [45]:
x2[0, :]

array([12,  1,  3,  7])

In [46]:
x2[0]

array([12,  1,  3,  7])

In [47]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [48]:
x2_sub = x2[:2, :2]

In [49]:
print(x2_sub)

[[12  1]
 [ 4  0]]


In [50]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [51]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [52]:
#P50↓

In [54]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [57]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [60]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [64]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [65]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [66]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [73]:
#P51↓

In [67]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [68]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [70]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]],)

In [71]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [72]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [74]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
y = np.array([[99],
              [99]])

In [78]:
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [79]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [80]:
grid = np.arange(16).reshape((4, 4))

In [81]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
upper, lower = np.vsplit(grid, [2])

In [84]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [85]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
