In [1]:
import numpy as np 


In [2]:
rng= np.random.default_rng(seed=1701)

In [3]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [4]:
values = rng.integers(1, 10, size=5)
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [5]:
big_array = rng.integers(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.07 s ± 7.85 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [9]:
%timeit (1.0 / big_array)

1.96 ms ± 101 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [15]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [19]:
x = np.arange(4)
print("x       =", x)
print("x + 5   =", x + 5)
print("x - 5   =", x - 5)
print("x * 2   =", x * 2)
print("x / 2   =", x / 2)
print("x // 2  =", x // 2) #切り捨て除算

x       = [0 1 2 3]
x + 5   = [5 6 7 8]
x - 5   = [-5 -4 -3 -2]
x * 2   = [0 2 4 6]
x / 2   = [0.  0.5 1.  1.5]
x // 2  = [0 0 1 1]


In [20]:
print("-x       =", -x)
print("x ** 2   =", x ** 2)
print("x % 2    =", x % 2)

-x       = [ 0 -1 -2 -3]
x ** 2   = [0 1 4 9]
x % 2    = [0 1 0 1]


In [22]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [23]:
np.add(x, 2)

array([2, 3, 4, 5])

In [27]:
np.mod(5, 135)

np.int64(5)

In [28]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [29]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [31]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [32]:
x = np.array([3 - 4j, 4-3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [33]:
theta = np.linspace(0, np.pi, 3)

In [34]:
print("theta       =", theta)
print("sin(theta)  =", np.sin(theta))
print("cos(theta)  =", np.cos(theta))
print("tan(theta)  =", np.tan(theta))

theta       = [0.         1.57079633 3.14159265]
sin(theta)  = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)  = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)  = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [36]:
x = [-1, 0, 1]
print("x           =", x)
print("arcsin(x)   =", np.arcsin(x))
print("arccos(x)   =", np.arccos(x))
print("arctan(x)   =", np.arctan(x))


x           = [-1, 0, 1]
arcsin(x)   = [-1.57079633  0.          1.57079633]
arccos(x)   = [3.14159265 1.57079633 0.        ]
arctan(x)   = [-0.78539816  0.          0.78539816]


In [39]:
x = [-1, 2, 3]
print("x         =", x)
print("e^x       =", np.exp(x))
print("2^x       =", np.exp2(x))
print("3^x       =", np.power(3., x))

x         = [-1, 2, 3]
e^x       = [ 0.36787944  7.3890561  20.08553692]
2^x       = [0.5 4.  8. ]
3^x       = [ 0.33333333  9.         27.        ]


In [40]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]
